site_name: Some app Docs
theme: readthedocs

nav:
  - Home: index.md
  - Indexation:
      - Getting Started: indexation/indexation.md
      - Jobs: indexation/jobs.md
      - Events: indexation/events.md

